goto start
:start
perl getjuanline.pl A091
perl getjuanline.pl A097
perl getjuanline.pl A098
perl getjuanline.pl A110
perl getjuanline.pl A111
perl getjuanline.pl A112
perl getjuanline.pl A114
perl getjuanline.pl A119
perl getjuanline.pl A120
perl getjuanline.pl A121
perl getjuanline.pl B01
perl getjuanline.pl B02
perl getjuanline.pl B03
perl getjuanline.pl B04
perl getjuanline.pl B05
perl getjuanline.pl B06
perl getjuanline.pl B07
perl getjuanline.pl B08
perl getjuanline.pl B09
perl getjuanline.pl B10
perl getjuanline.pl B11
perl getjuanline.pl B12
perl getjuanline.pl B13
perl getjuanline.pl B14
perl getjuanline.pl B15
perl getjuanline.pl B16
perl getjuanline.pl B17
perl getjuanline.pl B18
perl getjuanline.pl B19
perl getjuanline.pl B21
perl getjuanline.pl B22
perl getjuanline.pl B23
perl getjuanline.pl B24
perl getjuanline.pl B25
perl getjuanline.pl B26
perl getjuanline.pl B27
perl getjuanline.pl B28
perl getjuanline.pl B29
perl getjuanline.pl B30
perl getjuanline.pl B31
perl getjuanline.pl B32
perl getjuanline.pl B33
perl getjuanline.pl B34
perl getjuanline.pl B35
perl getjuanline.pl B36
perl getjuanline.pl C056
perl getjuanline.pl C057
perl getjuanline.pl C059
perl getjuanline.pl C071
perl getjuanline.pl C073
perl getjuanline.pl C077
perl getjuanline.pl C078
perl getjuanline.pl C097
perl getjuanline.pl C106
perl getjuanline.pl D01
perl getjuanline.pl D02
perl getjuanline.pl D03
perl getjuanline.pl D04
perl getjuanline.pl D05
perl getjuanline.pl D06
perl getjuanline.pl D07
perl getjuanline.pl D08
perl getjuanline.pl D09
perl getjuanline.pl D10
perl getjuanline.pl D11
perl getjuanline.pl D12
perl getjuanline.pl D13
perl getjuanline.pl D14
perl getjuanline.pl D15
perl getjuanline.pl D16
perl getjuanline.pl D17
perl getjuanline.pl D18
perl getjuanline.pl D19
perl getjuanline.pl D20
perl getjuanline.pl D21
perl getjuanline.pl D22
perl getjuanline.pl D23
perl getjuanline.pl D24
perl getjuanline.pl D25
perl getjuanline.pl D26
perl getjuanline.pl D27
perl getjuanline.pl D28
perl getjuanline.pl D29
perl getjuanline.pl D30
perl getjuanline.pl D31
perl getjuanline.pl D32
perl getjuanline.pl D33
perl getjuanline.pl D34
perl getjuanline.pl D35
perl getjuanline.pl D36
perl getjuanline.pl D37
perl getjuanline.pl D38
perl getjuanline.pl D39
perl getjuanline.pl D40
perl getjuanline.pl D41
perl getjuanline.pl D42
perl getjuanline.pl D43
perl getjuanline.pl D44
perl getjuanline.pl D45
perl getjuanline.pl D46
perl getjuanline.pl D47
perl getjuanline.pl D48
perl getjuanline.pl D49
perl getjuanline.pl D50
perl getjuanline.pl D51
perl getjuanline.pl D52
perl getjuanline.pl D53
perl getjuanline.pl D54
perl getjuanline.pl D55
perl getjuanline.pl D56
perl getjuanline.pl D57
perl getjuanline.pl D58
perl getjuanline.pl D59
perl getjuanline.pl D60
perl getjuanline.pl D61
perl getjuanline.pl D62
perl getjuanline.pl D63
perl getjuanline.pl D64
perl getjuanline.pl F01
perl getjuanline.pl F02
perl getjuanline.pl F03
perl getjuanline.pl F12
perl getjuanline.pl F24
perl getjuanline.pl F27
perl getjuanline.pl F28
perl getjuanline.pl F29
perl getjuanline.pl G052
perl getjuanline.pl G069
perl getjuanline.pl G083
perl getjuanline.pl G084
perl getjuanline.pl GA009
perl getjuanline.pl GA010
perl getjuanline.pl GA011
perl getjuanline.pl GA012
perl getjuanline.pl GA020
perl getjuanline.pl GA031
perl getjuanline.pl GA032
perl getjuanline.pl GA043
perl getjuanline.pl GA045
perl getjuanline.pl GA058
perl getjuanline.pl GA072
perl getjuanline.pl GA079
perl getjuanline.pl GA081
perl getjuanline.pl GA082
perl getjuanline.pl GA084
perl getjuanline.pl GA088
perl getjuanline.pl GA089
perl getjuanline.pl GA090
perl getjuanline.pl H01
perl getjuanline.pl I01
perl getjuanline.pl J01
perl getjuanline.pl J07
perl getjuanline.pl J10
perl getjuanline.pl J15
perl getjuanline.pl J19
perl getjuanline.pl J20
perl getjuanline.pl J21
perl getjuanline.pl J22
perl getjuanline.pl J23
perl getjuanline.pl J24
perl getjuanline.pl J25
perl getjuanline.pl J26
perl getjuanline.pl J27
perl getjuanline.pl J28
perl getjuanline.pl J29
perl getjuanline.pl J30
perl getjuanline.pl J31
perl getjuanline.pl J32
perl getjuanline.pl J33
perl getjuanline.pl J34
perl getjuanline.pl J35
perl getjuanline.pl J36
perl getjuanline.pl J37
perl getjuanline.pl J38
perl getjuanline.pl J39
perl getjuanline.pl J40
perl getjuanline.pl K05
perl getjuanline.pl K32
perl getjuanline.pl K34
perl getjuanline.pl K35
perl getjuanline.pl K38
perl getjuanline.pl K41
perl getjuanline.pl L115
perl getjuanline.pl L116
perl getjuanline.pl L130
perl getjuanline.pl L131
perl getjuanline.pl L132
perl getjuanline.pl L133
perl getjuanline.pl L135
perl getjuanline.pl L141
perl getjuanline.pl L143
perl getjuanline.pl L149
perl getjuanline.pl L153
perl getjuanline.pl L154
perl getjuanline.pl L155
perl getjuanline.pl L157
perl getjuanline.pl L158
perl getjuanline.pl L162
perl getjuanline.pl L164
perl getjuanline.pl M059
perl getjuanline.pl N01
perl getjuanline.pl N02
perl getjuanline.pl N03
perl getjuanline.pl N04
perl getjuanline.pl N05
perl getjuanline.pl N06
perl getjuanline.pl N07
perl getjuanline.pl N08
perl getjuanline.pl N09
perl getjuanline.pl N10
perl getjuanline.pl N11
perl getjuanline.pl N12
perl getjuanline.pl N13
perl getjuanline.pl N14
perl getjuanline.pl N15
perl getjuanline.pl N16
perl getjuanline.pl N17
perl getjuanline.pl N18
perl getjuanline.pl N19
perl getjuanline.pl N20
perl getjuanline.pl N21
perl getjuanline.pl N22
perl getjuanline.pl N23
perl getjuanline.pl N24
perl getjuanline.pl N25
perl getjuanline.pl N26
perl getjuanline.pl N27
perl getjuanline.pl N28
perl getjuanline.pl N29
perl getjuanline.pl N30
perl getjuanline.pl N31
perl getjuanline.pl N32
perl getjuanline.pl N33
perl getjuanline.pl N34
perl getjuanline.pl N35
perl getjuanline.pl N36
perl getjuanline.pl N37
perl getjuanline.pl N38
perl getjuanline.pl N39
perl getjuanline.pl N40
perl getjuanline.pl N41
perl getjuanline.pl N42
perl getjuanline.pl N43
perl getjuanline.pl N44
perl getjuanline.pl N45
perl getjuanline.pl N46
perl getjuanline.pl N47
perl getjuanline.pl N48
perl getjuanline.pl N49
perl getjuanline.pl N50
perl getjuanline.pl N51
perl getjuanline.pl N52
perl getjuanline.pl N53
perl getjuanline.pl N54
perl getjuanline.pl N55
perl getjuanline.pl N56
perl getjuanline.pl N57
perl getjuanline.pl N58
perl getjuanline.pl N59
perl getjuanline.pl N60
perl getjuanline.pl N61
perl getjuanline.pl N62
perl getjuanline.pl N63
perl getjuanline.pl N64
perl getjuanline.pl N65
perl getjuanline.pl N66
perl getjuanline.pl N67
perl getjuanline.pl N68
perl getjuanline.pl N69
perl getjuanline.pl N70
perl getjuanline.pl P154
perl getjuanline.pl P155
perl getjuanline.pl P167
perl getjuanline.pl P168
perl getjuanline.pl P174
perl getjuanline.pl P178
perl getjuanline.pl P179
perl getjuanline.pl P180
perl getjuanline.pl P181
perl getjuanline.pl P182
perl getjuanline.pl P183
perl getjuanline.pl P184
perl getjuanline.pl P185
perl getjuanline.pl P187
perl getjuanline.pl P189
perl getjuanline.pl S06
perl getjuanline.pl T01
perl getjuanline.pl T02
perl getjuanline.pl T03
perl getjuanline.pl T04
perl getjuanline.pl T05
perl getjuanline.pl T06
perl getjuanline.pl T07
perl getjuanline.pl T08
perl getjuanline.pl T09
perl getjuanline.pl T10
perl getjuanline.pl T11
perl getjuanline.pl T12
perl getjuanline.pl T13
perl getjuanline.pl T14
perl getjuanline.pl T15
perl getjuanline.pl T16
perl getjuanline.pl T17
perl getjuanline.pl T18
perl getjuanline.pl T19
perl getjuanline.pl T20
perl getjuanline.pl T21
perl getjuanline.pl T22
perl getjuanline.pl T23
perl getjuanline.pl T24
perl getjuanline.pl T25
perl getjuanline.pl T26
perl getjuanline.pl T27
perl getjuanline.pl T28
perl getjuanline.pl T29
perl getjuanline.pl T30
perl getjuanline.pl T31
perl getjuanline.pl T32
perl getjuanline.pl T33
perl getjuanline.pl T34
perl getjuanline.pl T35
perl getjuanline.pl T36
perl getjuanline.pl T37
perl getjuanline.pl T38
perl getjuanline.pl T39
perl getjuanline.pl T40
perl getjuanline.pl T41
perl getjuanline.pl T42
perl getjuanline.pl T43
perl getjuanline.pl T44
perl getjuanline.pl T45
perl getjuanline.pl T46
perl getjuanline.pl T47
perl getjuanline.pl T48
perl getjuanline.pl T49
perl getjuanline.pl T50
perl getjuanline.pl T51
perl getjuanline.pl T52
perl getjuanline.pl T53
perl getjuanline.pl T54
perl getjuanline.pl T55
perl getjuanline.pl T85
perl getjuanline.pl U205
perl getjuanline.pl U222
perl getjuanline.pl U223
perl getjuanline.pl W01
perl getjuanline.pl W02
perl getjuanline.pl W03
perl getjuanline.pl W04
perl getjuanline.pl W05
perl getjuanline.pl W06
perl getjuanline.pl W07
perl getjuanline.pl W08
perl getjuanline.pl W09
perl getjuanline.pl X01
perl getjuanline.pl X02
perl getjuanline.pl X03
perl getjuanline.pl X04
perl getjuanline.pl X05
perl getjuanline.pl X07
perl getjuanline.pl X08
perl getjuanline.pl X09
perl getjuanline.pl X10
perl getjuanline.pl X11
perl getjuanline.pl X12
perl getjuanline.pl X13
perl getjuanline.pl X14
perl getjuanline.pl X15
perl getjuanline.pl X16
perl getjuanline.pl X17
perl getjuanline.pl X18
perl getjuanline.pl X19
perl getjuanline.pl X20
perl getjuanline.pl X21
perl getjuanline.pl X22
perl getjuanline.pl X23
perl getjuanline.pl X24
perl getjuanline.pl X25
perl getjuanline.pl X26
perl getjuanline.pl X27
perl getjuanline.pl X28
perl getjuanline.pl X29
perl getjuanline.pl X30
perl getjuanline.pl X31
perl getjuanline.pl X32
perl getjuanline.pl X33
perl getjuanline.pl X34
perl getjuanline.pl X35
perl getjuanline.pl X36
perl getjuanline.pl X37
perl getjuanline.pl X38
perl getjuanline.pl X39
perl getjuanline.pl X40
perl getjuanline.pl X41
perl getjuanline.pl X42
perl getjuanline.pl X43
perl getjuanline.pl X44
perl getjuanline.pl X45
perl getjuanline.pl X46
perl getjuanline.pl X47
perl getjuanline.pl X48
perl getjuanline.pl X49
perl getjuanline.pl X50
perl getjuanline.pl X51
perl getjuanline.pl X53
perl getjuanline.pl X54
perl getjuanline.pl X55
perl getjuanline.pl X56
perl getjuanline.pl X57
perl getjuanline.pl X58
perl getjuanline.pl X59
perl getjuanline.pl X60
perl getjuanline.pl X61
perl getjuanline.pl X62
perl getjuanline.pl X63
perl getjuanline.pl X64
perl getjuanline.pl X65
perl getjuanline.pl X66
perl getjuanline.pl X67
perl getjuanline.pl X68
perl getjuanline.pl X69
perl getjuanline.pl X70
perl getjuanline.pl X71
perl getjuanline.pl X72
perl getjuanline.pl X73
perl getjuanline.pl X74
perl getjuanline.pl X75
perl getjuanline.pl X76
perl getjuanline.pl X77
perl getjuanline.pl X78
perl getjuanline.pl X79
perl getjuanline.pl X80
perl getjuanline.pl X81
perl getjuanline.pl X82
perl getjuanline.pl X83
perl getjuanline.pl X84
perl getjuanline.pl X85
perl getjuanline.pl X86
perl getjuanline.pl X87
perl getjuanline.pl X88

goto end
perl getjuanline.pl ZY01
perl getjuanline.pl ZY02
perl getjuanline.pl ZY03
perl getjuanline.pl ZY04
perl getjuanline.pl ZY05
perl getjuanline.pl ZY06
perl getjuanline.pl ZY07
perl getjuanline.pl ZY08
perl getjuanline.pl ZY09
perl getjuanline.pl ZY10
perl getjuanline.pl ZY11
perl getjuanline.pl ZY12
perl getjuanline.pl ZY13
perl getjuanline.pl ZY14
perl getjuanline.pl ZY15
perl getjuanline.pl ZY16
perl getjuanline.pl ZY17
perl getjuanline.pl ZY18
perl getjuanline.pl ZY19
perl getjuanline.pl ZY20
perl getjuanline.pl ZY21
perl getjuanline.pl ZY22
perl getjuanline.pl ZY23
perl getjuanline.pl ZY24
perl getjuanline.pl ZY25
perl getjuanline.pl ZY26
perl getjuanline.pl ZY27
perl getjuanline.pl ZY28
perl getjuanline.pl ZY29
perl getjuanline.pl ZY30
perl getjuanline.pl ZY31
perl getjuanline.pl ZY32
perl getjuanline.pl ZY33
perl getjuanline.pl ZY34
perl getjuanline.pl ZY35
perl getjuanline.pl ZY36
perl getjuanline.pl ZY37
perl getjuanline.pl ZY38
perl getjuanline.pl ZY39
perl getjuanline.pl ZY40
perl getjuanline.pl ZY41
perl getjuanline.pl ZY42
perl getjuanline.pl ZY43
perl getjuanline.pl ZY44

perl getjuanline.pl DA01
perl getjuanline.pl DA02
perl getjuanline.pl DA03
perl getjuanline.pl DA04
perl getjuanline.pl DA05
perl getjuanline.pl DA06
perl getjuanline.pl DA07
perl getjuanline.pl DA08
perl getjuanline.pl DA09
perl getjuanline.pl DA10
perl getjuanline.pl DA11
perl getjuanline.pl DA12
perl getjuanline.pl DA13
perl getjuanline.pl DA14
perl getjuanline.pl DA15
perl getjuanline.pl DA16
perl getjuanline.pl DA17
perl getjuanline.pl DA18

:end